# 1. Introduction

## Book Description

This book addresses the collection and use of data for decision making and assessment in learning and human performance contexts. Students will get hands-on experience with small data sets and will learn how big data sets are collected and used. The book will explore the role that analytics plays in education and related fields, identify the types of questions that might be answered via both quantitative and qualitative analytics, and engage in analytic- related problem solving. This book will examine case studies and provide students with practice using a variety of tools and services that can help them collect and analyze learning and web data. There are no pre-requisites, and although data will be used prior experience with statistics or research design is not necessary.

## Learning Objectives

At the completion of this book, students will be able to:

1. Discuss major concepts related to analytics.
2. Discuss the application of analytics to the fields of instructional systems design and performance technology.
3. Apply the major concepts related to analytics to solving real world problems.
4. Identify real world problems that might be addressed via analytics.
5. Align problems with appropriate data sources, data collection methods, and analytic methods.
6. Select the most appropriate analytic tool for a given context.
7. Collect analytic data in a systematic manner.
8. Analyze and interpret systematically collected analytic data.
9. Develop context-appropriate reports that indicate how analytics address a particular problem.

## A Note on Data Privacy

Your personal data is valuable and important, which is why it is often collected by the digital tools you use in your educational activities. To better understand how and why your data is collected, the potential risks of this collection, and how to better protect your personal data, consider asking yourself the following questions:

    What types of personal data do you think are collected through your use of digital tools for educational activities?
    What value does your personal data have for different contexts and entities? Consider how your data might be valued by your instructor, the institution, yourself, and companies.
    Who owns your personal data, who can sell it, and who can use it?
    Do you have concerns about how your personal data can be used? If so, what are they?
    Are there aspects of your identity or life that you feel would put you in a place of special vulnerability if certain data were known about you or used against you?

If after asking yourself these questions you have concerns, I invite you to reach out to me to discuss them. I may not have easy answers to the questions or concerns that you bring to me (often in these matters no one has these answers), but I will happily explore them further with you or find someone more knowledgeable who can help answer your questions.

[Please read this article by Autumm Caines and Erin Glass on EduCause](https://er.educause.edu/articles/2019/10/education-before-regulation-empowering-students-to-question-their-data-privacy) for further reflection.
